skillMetadata:
  sections:
    - name: Google Classroom
      fields:
        - type: label
          label: At first you have to enable the Google Classroom API.
          value: ""
        - name: GoogleClassroomAPI
          type: oauth
          value: 1
    - name: